// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingService.proto

package ds.bookingService;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.bookingService.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
