// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2Booking.proto

package ca.railway.bookingService2;

public interface BookingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.railway.bookingService2.Booking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trainNo = 1;</code>
   */
  int getTrainNo();

  /**
   * <code>string confirmationMsg = 2;</code>
   */
  java.lang.String getConfirmationMsg();
  /**
   * <code>string confirmationMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationMsgBytes();
}
