// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2Booking.proto

package ca.railway.bookingService2;

public interface BookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.railway.bookingService2.BookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trainNo = 1;</code>
   */
  int getTrainNo();

  /**
   * <code>string specialRequestMsg = 2;</code>
   */
  java.lang.String getSpecialRequestMsg();
  /**
   * <code>string specialRequestMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getSpecialRequestMsgBytes();
}
