// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2Booking.proto

package ca.railway.bookingService2;

public interface BookingReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.railway.bookingService2.BookingReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmationMsg = 1;</code>
   */
  java.lang.String getConfirmationMsg();
  /**
   * <code>string confirmationMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationMsgBytes();
}
