// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2Booking.proto

package ca.railway.bookingService2;

public final class BookingServiceImpl {
  private BookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_railway_bookingService2_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_railway_bookingService2_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_railway_bookingService2_LoginReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_railway_bookingService2_LoginReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025service2Booking.proto\022\032ca.railway.book" +
      "ingService2\"2\n\014LoginRequest\022\020\n\010username\030" +
      "\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\035\n\nLoginReply\022\017\n" +
      "\007message\030\001 \001(\t2m\n\016BookingService\022[\n\005logi" +
      "n\022(.ca.railway.bookingService2.LoginRequ" +
      "est\032&.ca.railway.bookingService2.LoginRe" +
      "ply\"\000B2\n\032ca.railway.bookingService2B\022Boo" +
      "kingServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ca_railway_bookingService2_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_railway_bookingService2_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_railway_bookingService2_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_ca_railway_bookingService2_LoginReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ca_railway_bookingService2_LoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_railway_bookingService2_LoginReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
