// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2Booking.proto

package ca.railway.timetableService1;

public interface BookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:timetableService1.BookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trainNo = 1;</code>
   */
  int getTrainNo();

  /**
   * <code>string specialRequest = 2;</code>
   */
  java.lang.String getSpecialRequest();
  /**
   * <code>string specialRequest = 2;</code>
   */
  com.google.protobuf.ByteString
      getSpecialRequestBytes();
}
