// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1Timetable.proto

package ca.railway.timetableService1;

public interface StationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:timetableService1.Stations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string departStation = 1;</code>
   */
  java.lang.String getDepartStation();
  /**
   * <code>string departStation = 1;</code>
   */
  com.google.protobuf.ByteString
      getDepartStationBytes();

  /**
   * <code>string arrivalStation = 2;</code>
   */
  java.lang.String getArrivalStation();
  /**
   * <code>string arrivalStation = 2;</code>
   */
  com.google.protobuf.ByteString
      getArrivalStationBytes();
}
