// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1Timetable.proto

package ca.railway.timetableService1;

public interface TrainNoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:timetableService1.TrainNo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trainNo = 1;</code>
   */
  int getTrainNo();
}
