// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1Timetable.proto

package ca.railway.timetableService1;

public interface TrainDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:timetableService1.TrainDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time = 1;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>float price = 2;</code>
   */
  float getPrice();

  /**
   * <code>int32 trainNo = 3;</code>
   */
  int getTrainNo();

  /**
   * <code>string msg = 4;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 4;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
