// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3Support.proto

package ca.railway.supportService3;

public interface complaintMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supportService3.complaintMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string complaint = 1;</code>
   */
  java.lang.String getComplaint();
  /**
   * <code>string complaint = 1;</code>
   */
  com.google.protobuf.ByteString
      getComplaintBytes();
}
