// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3Support.proto

package ca.railway.supportService3;

public interface emergencyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supportService3.emergencyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string safetyDetails = 1;</code>
   */
  java.lang.String getSafetyDetails();
  /**
   * <code>string safetyDetails = 1;</code>
   */
  com.google.protobuf.ByteString
      getSafetyDetailsBytes();

  /**
   * <code>int32 policeNo = 2;</code>
   */
  int getPoliceNo();

  /**
   * <code>int32 paramedicNo = 3;</code>
   */
  int getParamedicNo();
}
