// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3Support.proto

package ca.railway.supportService3;

/**
 * Protobuf type {@code supportService3.emergencyResponse}
 */
public  final class emergencyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:supportService3.emergencyResponse)
    emergencyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use emergencyResponse.newBuilder() to construct.
  private emergencyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private emergencyResponse() {
    safetyDetails_ = "";
    policeNo_ = 0;
    paramedicNo_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private emergencyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            safetyDetails_ = s;
            break;
          }
          case 16: {

            policeNo_ = input.readInt32();
            break;
          }
          case 24: {

            paramedicNo_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.railway.supportService3.SupportServiceImpl.internal_static_supportService3_emergencyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.railway.supportService3.SupportServiceImpl.internal_static_supportService3_emergencyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.railway.supportService3.emergencyResponse.class, ca.railway.supportService3.emergencyResponse.Builder.class);
  }

  public static final int SAFETYDETAILS_FIELD_NUMBER = 1;
  private volatile java.lang.Object safetyDetails_;
  /**
   * <code>string safetyDetails = 1;</code>
   */
  public java.lang.String getSafetyDetails() {
    java.lang.Object ref = safetyDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      safetyDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string safetyDetails = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSafetyDetailsBytes() {
    java.lang.Object ref = safetyDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      safetyDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POLICENO_FIELD_NUMBER = 2;
  private int policeNo_;
  /**
   * <code>int32 policeNo = 2;</code>
   */
  public int getPoliceNo() {
    return policeNo_;
  }

  public static final int PARAMEDICNO_FIELD_NUMBER = 3;
  private int paramedicNo_;
  /**
   * <code>int32 paramedicNo = 3;</code>
   */
  public int getParamedicNo() {
    return paramedicNo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSafetyDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, safetyDetails_);
    }
    if (policeNo_ != 0) {
      output.writeInt32(2, policeNo_);
    }
    if (paramedicNo_ != 0) {
      output.writeInt32(3, paramedicNo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSafetyDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, safetyDetails_);
    }
    if (policeNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, policeNo_);
    }
    if (paramedicNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, paramedicNo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.railway.supportService3.emergencyResponse)) {
      return super.equals(obj);
    }
    ca.railway.supportService3.emergencyResponse other = (ca.railway.supportService3.emergencyResponse) obj;

    boolean result = true;
    result = result && getSafetyDetails()
        .equals(other.getSafetyDetails());
    result = result && (getPoliceNo()
        == other.getPoliceNo());
    result = result && (getParamedicNo()
        == other.getParamedicNo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SAFETYDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getSafetyDetails().hashCode();
    hash = (37 * hash) + POLICENO_FIELD_NUMBER;
    hash = (53 * hash) + getPoliceNo();
    hash = (37 * hash) + PARAMEDICNO_FIELD_NUMBER;
    hash = (53 * hash) + getParamedicNo();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.railway.supportService3.emergencyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.railway.supportService3.emergencyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.railway.supportService3.emergencyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.railway.supportService3.emergencyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.railway.supportService3.emergencyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code supportService3.emergencyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:supportService3.emergencyResponse)
      ca.railway.supportService3.emergencyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.railway.supportService3.SupportServiceImpl.internal_static_supportService3_emergencyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.railway.supportService3.SupportServiceImpl.internal_static_supportService3_emergencyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.railway.supportService3.emergencyResponse.class, ca.railway.supportService3.emergencyResponse.Builder.class);
    }

    // Construct using ca.railway.supportService3.emergencyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      safetyDetails_ = "";

      policeNo_ = 0;

      paramedicNo_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.railway.supportService3.SupportServiceImpl.internal_static_supportService3_emergencyResponse_descriptor;
    }

    @java.lang.Override
    public ca.railway.supportService3.emergencyResponse getDefaultInstanceForType() {
      return ca.railway.supportService3.emergencyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ca.railway.supportService3.emergencyResponse build() {
      ca.railway.supportService3.emergencyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.railway.supportService3.emergencyResponse buildPartial() {
      ca.railway.supportService3.emergencyResponse result = new ca.railway.supportService3.emergencyResponse(this);
      result.safetyDetails_ = safetyDetails_;
      result.policeNo_ = policeNo_;
      result.paramedicNo_ = paramedicNo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.railway.supportService3.emergencyResponse) {
        return mergeFrom((ca.railway.supportService3.emergencyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.railway.supportService3.emergencyResponse other) {
      if (other == ca.railway.supportService3.emergencyResponse.getDefaultInstance()) return this;
      if (!other.getSafetyDetails().isEmpty()) {
        safetyDetails_ = other.safetyDetails_;
        onChanged();
      }
      if (other.getPoliceNo() != 0) {
        setPoliceNo(other.getPoliceNo());
      }
      if (other.getParamedicNo() != 0) {
        setParamedicNo(other.getParamedicNo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.railway.supportService3.emergencyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.railway.supportService3.emergencyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object safetyDetails_ = "";
    /**
     * <code>string safetyDetails = 1;</code>
     */
    public java.lang.String getSafetyDetails() {
      java.lang.Object ref = safetyDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        safetyDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string safetyDetails = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSafetyDetailsBytes() {
      java.lang.Object ref = safetyDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        safetyDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string safetyDetails = 1;</code>
     */
    public Builder setSafetyDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      safetyDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string safetyDetails = 1;</code>
     */
    public Builder clearSafetyDetails() {
      
      safetyDetails_ = getDefaultInstance().getSafetyDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string safetyDetails = 1;</code>
     */
    public Builder setSafetyDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      safetyDetails_ = value;
      onChanged();
      return this;
    }

    private int policeNo_ ;
    /**
     * <code>int32 policeNo = 2;</code>
     */
    public int getPoliceNo() {
      return policeNo_;
    }
    /**
     * <code>int32 policeNo = 2;</code>
     */
    public Builder setPoliceNo(int value) {
      
      policeNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 policeNo = 2;</code>
     */
    public Builder clearPoliceNo() {
      
      policeNo_ = 0;
      onChanged();
      return this;
    }

    private int paramedicNo_ ;
    /**
     * <code>int32 paramedicNo = 3;</code>
     */
    public int getParamedicNo() {
      return paramedicNo_;
    }
    /**
     * <code>int32 paramedicNo = 3;</code>
     */
    public Builder setParamedicNo(int value) {
      
      paramedicNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 paramedicNo = 3;</code>
     */
    public Builder clearParamedicNo() {
      
      paramedicNo_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:supportService3.emergencyResponse)
  }

  // @@protoc_insertion_point(class_scope:supportService3.emergencyResponse)
  private static final ca.railway.supportService3.emergencyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.railway.supportService3.emergencyResponse();
  }

  public static ca.railway.supportService3.emergencyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<emergencyResponse>
      PARSER = new com.google.protobuf.AbstractParser<emergencyResponse>() {
    @java.lang.Override
    public emergencyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new emergencyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<emergencyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<emergencyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.railway.supportService3.emergencyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

