// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3Support.proto

package ca.railway.supportService3;

public interface emergencyReportBoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supportService3.emergencyReportBool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool emergency = 1;</code>
   */
  boolean getEmergency();
}
