// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3Support.proto

package ca.railway.supportService3;

public final class SupportServiceImpl {
  private SupportServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supportService3_complaintMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supportService3_complaintMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supportService3_complaintConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supportService3_complaintConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supportService3_emergencyReportBool_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supportService3_emergencyReportBool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supportService3_emergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supportService3_emergencyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025service3Support.proto\022\017supportService3" +
      "\"!\n\014complaintMsg\022\021\n\tcomplaint\030\001 \001(\t\"&\n\025c" +
      "omplaintConfirmation\022\r\n\005reply\030\001 \001(\t\"(\n\023e" +
      "mergencyReportBool\022\021\n\temergency\030\001 \001(\010\"Q\n" +
      "\021emergencyResponse\022\025\n\rsafetyDetails\030\001 \001(" +
      "\t\022\020\n\010policeNo\030\002 \001(\005\022\023\n\013paramedicNo\030\003 \001(\005" +
      "2\301\001\n\016SupportService\022T\n\tcomplaint\022\035.suppo" +
      "rtService3.complaintMsg\032&.supportService" +
      "3.complaintConfirmation\"\000\022Y\n\temergency\022$" +
      ".supportService3.emergencyReportBool\032\".s" +
      "upportService3.emergencyResponse\"\0000\001B2\n\032" +
      "ca.railway.supportService3B\022SupportServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_supportService3_complaintMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_supportService3_complaintMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supportService3_complaintMsg_descriptor,
        new java.lang.String[] { "Complaint", });
    internal_static_supportService3_complaintConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_supportService3_complaintConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supportService3_complaintConfirmation_descriptor,
        new java.lang.String[] { "Reply", });
    internal_static_supportService3_emergencyReportBool_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_supportService3_emergencyReportBool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supportService3_emergencyReportBool_descriptor,
        new java.lang.String[] { "Emergency", });
    internal_static_supportService3_emergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_supportService3_emergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supportService3_emergencyResponse_descriptor,
        new java.lang.String[] { "SafetyDetails", "PoliceNo", "ParamedicNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
