// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetableService.proto

package ds.timetableService;

public interface DelaysBoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.DelaysBool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool delaysBool = 1;</code>
   */
  boolean getDelaysBool();
}
