// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetableService.proto

package ds.timetableService;

public final class TimetableServiceImpl {
  private TimetableServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Stations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Stations_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TrainDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TrainDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TrainNo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TrainNo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_DelaysBool_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_DelaysBool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TrainAmenities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TrainAmenities_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026timetableService.proto\022\010service1\"9\n\010St" +
      "ations\022\025\n\rdepartStation\030\001 \001(\t\022\026\n\016arrival" +
      "Station\030\002 \001(\t\"<\n\014TrainDetails\022\014\n\004time\030\001 " +
      "\001(\t\022\r\n\005price\030\002 \001(\001\022\017\n\007trainNo\030\003 \001(\005\"\032\n\007T" +
      "rainNo\022\017\n\007trainNo\030\001 \001(\005\" \n\nDelaysBool\022\022\n" +
      "\ndelaysBool\030\001 \001(\010\"I\n\016TrainAmenities\022\020\n\010c" +
      "atering\030\001 \001(\t\022\020\n\010bikeSlot\030\002 \001(\t\022\023\n\013petsA" +
      "llowed\030\003 \001(\t2\310\001\n\020timetableService\022A\n\rVie" +
      "wTimetable\022\022.service1.Stations\032\026.service" +
      "1.TrainDetails\"\000(\0010\001\0223\n\006delays\022\021.service" +
      "1.TrainNo\032\024.service1.DelaysBool\"\000\022<\n\tame" +
      "nities\022\021.service1.TrainNo\032\030.service1.Tra" +
      "inAmenities\"\0000\001B-\n\023ds.timetableServiceB\024" +
      "TimetableServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_Stations_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_Stations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Stations_descriptor,
        new java.lang.String[] { "DepartStation", "ArrivalStation", });
    internal_static_service1_TrainDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_TrainDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TrainDetails_descriptor,
        new java.lang.String[] { "Time", "Price", "TrainNo", });
    internal_static_service1_TrainNo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_TrainNo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TrainNo_descriptor,
        new java.lang.String[] { "TrainNo", });
    internal_static_service1_DelaysBool_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_DelaysBool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_DelaysBool_descriptor,
        new java.lang.String[] { "DelaysBool", });
    internal_static_service1_TrainAmenities_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_TrainAmenities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TrainAmenities_descriptor,
        new java.lang.String[] { "Catering", "BikeSlot", "PetsAllowed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
