// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetableService.proto

package ds.timetableService;

public interface TrainNoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TrainNo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trainNo = 1;</code>
   */
  int getTrainNo();
}
