// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetableService.proto

package ds.timetableService;

/**
 * Protobuf type {@code service1.TrainAmenities}
 */
public  final class TrainAmenities extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.TrainAmenities)
    TrainAmenitiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrainAmenities.newBuilder() to construct.
  private TrainAmenities(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrainAmenities() {
    catering_ = "";
    bikeSlot_ = "";
    petsAllowed_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrainAmenities(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            catering_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bikeSlot_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            petsAllowed_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.timetableService.TimetableServiceImpl.internal_static_service1_TrainAmenities_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.timetableService.TimetableServiceImpl.internal_static_service1_TrainAmenities_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.timetableService.TrainAmenities.class, ds.timetableService.TrainAmenities.Builder.class);
  }

  public static final int CATERING_FIELD_NUMBER = 1;
  private volatile java.lang.Object catering_;
  /**
   * <code>string catering = 1;</code>
   */
  public java.lang.String getCatering() {
    java.lang.Object ref = catering_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      catering_ = s;
      return s;
    }
  }
  /**
   * <code>string catering = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCateringBytes() {
    java.lang.Object ref = catering_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      catering_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIKESLOT_FIELD_NUMBER = 2;
  private volatile java.lang.Object bikeSlot_;
  /**
   * <code>string bikeSlot = 2;</code>
   */
  public java.lang.String getBikeSlot() {
    java.lang.Object ref = bikeSlot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bikeSlot_ = s;
      return s;
    }
  }
  /**
   * <code>string bikeSlot = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBikeSlotBytes() {
    java.lang.Object ref = bikeSlot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bikeSlot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETSALLOWED_FIELD_NUMBER = 3;
  private volatile java.lang.Object petsAllowed_;
  /**
   * <code>string petsAllowed = 3;</code>
   */
  public java.lang.String getPetsAllowed() {
    java.lang.Object ref = petsAllowed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petsAllowed_ = s;
      return s;
    }
  }
  /**
   * <code>string petsAllowed = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPetsAllowedBytes() {
    java.lang.Object ref = petsAllowed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petsAllowed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCateringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, catering_);
    }
    if (!getBikeSlotBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bikeSlot_);
    }
    if (!getPetsAllowedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, petsAllowed_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCateringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, catering_);
    }
    if (!getBikeSlotBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bikeSlot_);
    }
    if (!getPetsAllowedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, petsAllowed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.timetableService.TrainAmenities)) {
      return super.equals(obj);
    }
    ds.timetableService.TrainAmenities other = (ds.timetableService.TrainAmenities) obj;

    boolean result = true;
    result = result && getCatering()
        .equals(other.getCatering());
    result = result && getBikeSlot()
        .equals(other.getBikeSlot());
    result = result && getPetsAllowed()
        .equals(other.getPetsAllowed());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CATERING_FIELD_NUMBER;
    hash = (53 * hash) + getCatering().hashCode();
    hash = (37 * hash) + BIKESLOT_FIELD_NUMBER;
    hash = (53 * hash) + getBikeSlot().hashCode();
    hash = (37 * hash) + PETSALLOWED_FIELD_NUMBER;
    hash = (53 * hash) + getPetsAllowed().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.timetableService.TrainAmenities parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.timetableService.TrainAmenities parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.timetableService.TrainAmenities parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.timetableService.TrainAmenities parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.timetableService.TrainAmenities parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.timetableService.TrainAmenities parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.timetableService.TrainAmenities prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.TrainAmenities}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.TrainAmenities)
      ds.timetableService.TrainAmenitiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.timetableService.TimetableServiceImpl.internal_static_service1_TrainAmenities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.timetableService.TimetableServiceImpl.internal_static_service1_TrainAmenities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.timetableService.TrainAmenities.class, ds.timetableService.TrainAmenities.Builder.class);
    }

    // Construct using ds.timetableService.TrainAmenities.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      catering_ = "";

      bikeSlot_ = "";

      petsAllowed_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.timetableService.TimetableServiceImpl.internal_static_service1_TrainAmenities_descriptor;
    }

    @java.lang.Override
    public ds.timetableService.TrainAmenities getDefaultInstanceForType() {
      return ds.timetableService.TrainAmenities.getDefaultInstance();
    }

    @java.lang.Override
    public ds.timetableService.TrainAmenities build() {
      ds.timetableService.TrainAmenities result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.timetableService.TrainAmenities buildPartial() {
      ds.timetableService.TrainAmenities result = new ds.timetableService.TrainAmenities(this);
      result.catering_ = catering_;
      result.bikeSlot_ = bikeSlot_;
      result.petsAllowed_ = petsAllowed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.timetableService.TrainAmenities) {
        return mergeFrom((ds.timetableService.TrainAmenities)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.timetableService.TrainAmenities other) {
      if (other == ds.timetableService.TrainAmenities.getDefaultInstance()) return this;
      if (!other.getCatering().isEmpty()) {
        catering_ = other.catering_;
        onChanged();
      }
      if (!other.getBikeSlot().isEmpty()) {
        bikeSlot_ = other.bikeSlot_;
        onChanged();
      }
      if (!other.getPetsAllowed().isEmpty()) {
        petsAllowed_ = other.petsAllowed_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.timetableService.TrainAmenities parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.timetableService.TrainAmenities) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object catering_ = "";
    /**
     * <code>string catering = 1;</code>
     */
    public java.lang.String getCatering() {
      java.lang.Object ref = catering_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catering_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string catering = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCateringBytes() {
      java.lang.Object ref = catering_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catering_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string catering = 1;</code>
     */
    public Builder setCatering(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      catering_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string catering = 1;</code>
     */
    public Builder clearCatering() {
      
      catering_ = getDefaultInstance().getCatering();
      onChanged();
      return this;
    }
    /**
     * <code>string catering = 1;</code>
     */
    public Builder setCateringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      catering_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bikeSlot_ = "";
    /**
     * <code>string bikeSlot = 2;</code>
     */
    public java.lang.String getBikeSlot() {
      java.lang.Object ref = bikeSlot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bikeSlot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bikeSlot = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBikeSlotBytes() {
      java.lang.Object ref = bikeSlot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bikeSlot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bikeSlot = 2;</code>
     */
    public Builder setBikeSlot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bikeSlot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bikeSlot = 2;</code>
     */
    public Builder clearBikeSlot() {
      
      bikeSlot_ = getDefaultInstance().getBikeSlot();
      onChanged();
      return this;
    }
    /**
     * <code>string bikeSlot = 2;</code>
     */
    public Builder setBikeSlotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bikeSlot_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object petsAllowed_ = "";
    /**
     * <code>string petsAllowed = 3;</code>
     */
    public java.lang.String getPetsAllowed() {
      java.lang.Object ref = petsAllowed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petsAllowed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string petsAllowed = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPetsAllowedBytes() {
      java.lang.Object ref = petsAllowed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petsAllowed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petsAllowed = 3;</code>
     */
    public Builder setPetsAllowed(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petsAllowed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petsAllowed = 3;</code>
     */
    public Builder clearPetsAllowed() {
      
      petsAllowed_ = getDefaultInstance().getPetsAllowed();
      onChanged();
      return this;
    }
    /**
     * <code>string petsAllowed = 3;</code>
     */
    public Builder setPetsAllowedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petsAllowed_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.TrainAmenities)
  }

  // @@protoc_insertion_point(class_scope:service1.TrainAmenities)
  private static final ds.timetableService.TrainAmenities DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.timetableService.TrainAmenities();
  }

  public static ds.timetableService.TrainAmenities getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrainAmenities>
      PARSER = new com.google.protobuf.AbstractParser<TrainAmenities>() {
    @java.lang.Override
    public TrainAmenities parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrainAmenities(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrainAmenities> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrainAmenities> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.timetableService.TrainAmenities getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

