// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetableService.proto

package ds.timetableService;

public interface TrainAmenitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TrainAmenities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string catering = 1;</code>
   */
  java.lang.String getCatering();
  /**
   * <code>string catering = 1;</code>
   */
  com.google.protobuf.ByteString
      getCateringBytes();

  /**
   * <code>string bikeSlot = 2;</code>
   */
  java.lang.String getBikeSlot();
  /**
   * <code>string bikeSlot = 2;</code>
   */
  com.google.protobuf.ByteString
      getBikeSlotBytes();

  /**
   * <code>string petsAllowed = 3;</code>
   */
  java.lang.String getPetsAllowed();
  /**
   * <code>string petsAllowed = 3;</code>
   */
  com.google.protobuf.ByteString
      getPetsAllowedBytes();
}
