// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maths.proto

package ds.examples.maths;

public final class MathServiceImpl {
  private MathServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_Stations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_Stations_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_TrainDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_TrainDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013maths.proto\022\005maths\"9\n\010Stations\022\025\n\rdepa" +
      "rtStation\030\001 \001(\t\022\026\n\016arrivalStation\030\002 \001(\t\"" +
      "<\n\014TrainDetails\022\014\n\004time\030\001 \001(\t\022\r\n\005price\030\002" +
      " \001(\002\022\017\n\007trainNo\030\003 \001(\0052F\n\013MathService\0227\n\r" +
      "viewTimetable\022\017.maths.Stations\032\023.maths.T" +
      "rainDetails\"\000B&\n\021ds.examples.mathsB\017Math" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_maths_Stations_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maths_Stations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_Stations_descriptor,
        new java.lang.String[] { "DepartStation", "ArrivalStation", });
    internal_static_maths_TrainDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maths_TrainDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_TrainDetails_descriptor,
        new java.lang.String[] { "Time", "Price", "TrainNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
