// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1Timetable.proto

package ds.examples.maths;

public interface PricingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maths.Pricing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string price = 1;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 1;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();
}
