// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maths.proto

package ds.examples.maths;

/**
 * Protobuf type {@code maths.Stations}
 */
public  final class Stations extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maths.Stations)
    StationsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Stations.newBuilder() to construct.
  private Stations(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Stations() {
    departStation_ = "";
    arrivalStation_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Stations(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            departStation_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            arrivalStation_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.examples.maths.MathServiceImpl.internal_static_maths_Stations_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.examples.maths.MathServiceImpl.internal_static_maths_Stations_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.examples.maths.Stations.class, ds.examples.maths.Stations.Builder.class);
  }

  public static final int DEPARTSTATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object departStation_;
  /**
   * <code>string departStation = 1;</code>
   */
  public java.lang.String getDepartStation() {
    java.lang.Object ref = departStation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departStation_ = s;
      return s;
    }
  }
  /**
   * <code>string departStation = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDepartStationBytes() {
    java.lang.Object ref = departStation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      departStation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVALSTATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object arrivalStation_;
  /**
   * <code>string arrivalStation = 2;</code>
   */
  public java.lang.String getArrivalStation() {
    java.lang.Object ref = arrivalStation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrivalStation_ = s;
      return s;
    }
  }
  /**
   * <code>string arrivalStation = 2;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalStationBytes() {
    java.lang.Object ref = arrivalStation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalStation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDepartStationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, departStation_);
    }
    if (!getArrivalStationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, arrivalStation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDepartStationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, departStation_);
    }
    if (!getArrivalStationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, arrivalStation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.examples.maths.Stations)) {
      return super.equals(obj);
    }
    ds.examples.maths.Stations other = (ds.examples.maths.Stations) obj;

    boolean result = true;
    result = result && getDepartStation()
        .equals(other.getDepartStation());
    result = result && getArrivalStation()
        .equals(other.getArrivalStation());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEPARTSTATION_FIELD_NUMBER;
    hash = (53 * hash) + getDepartStation().hashCode();
    hash = (37 * hash) + ARRIVALSTATION_FIELD_NUMBER;
    hash = (53 * hash) + getArrivalStation().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.examples.maths.Stations parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.maths.Stations parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.maths.Stations parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.maths.Stations parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.maths.Stations parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.maths.Stations parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.maths.Stations parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.maths.Stations parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.maths.Stations parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.examples.maths.Stations parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.maths.Stations parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.maths.Stations parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.examples.maths.Stations prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code maths.Stations}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maths.Stations)
      ds.examples.maths.StationsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.examples.maths.MathServiceImpl.internal_static_maths_Stations_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.examples.maths.MathServiceImpl.internal_static_maths_Stations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.examples.maths.Stations.class, ds.examples.maths.Stations.Builder.class);
    }

    // Construct using ds.examples.maths.Stations.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      departStation_ = "";

      arrivalStation_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.examples.maths.MathServiceImpl.internal_static_maths_Stations_descriptor;
    }

    @java.lang.Override
    public ds.examples.maths.Stations getDefaultInstanceForType() {
      return ds.examples.maths.Stations.getDefaultInstance();
    }

    @java.lang.Override
    public ds.examples.maths.Stations build() {
      ds.examples.maths.Stations result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.examples.maths.Stations buildPartial() {
      ds.examples.maths.Stations result = new ds.examples.maths.Stations(this);
      result.departStation_ = departStation_;
      result.arrivalStation_ = arrivalStation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.examples.maths.Stations) {
        return mergeFrom((ds.examples.maths.Stations)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.examples.maths.Stations other) {
      if (other == ds.examples.maths.Stations.getDefaultInstance()) return this;
      if (!other.getDepartStation().isEmpty()) {
        departStation_ = other.departStation_;
        onChanged();
      }
      if (!other.getArrivalStation().isEmpty()) {
        arrivalStation_ = other.arrivalStation_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.examples.maths.Stations parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.examples.maths.Stations) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object departStation_ = "";
    /**
     * <code>string departStation = 1;</code>
     */
    public java.lang.String getDepartStation() {
      java.lang.Object ref = departStation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departStation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string departStation = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDepartStationBytes() {
      java.lang.Object ref = departStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departStation = 1;</code>
     */
    public Builder setDepartStation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      departStation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string departStation = 1;</code>
     */
    public Builder clearDepartStation() {
      
      departStation_ = getDefaultInstance().getDepartStation();
      onChanged();
      return this;
    }
    /**
     * <code>string departStation = 1;</code>
     */
    public Builder setDepartStationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      departStation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object arrivalStation_ = "";
    /**
     * <code>string arrivalStation = 2;</code>
     */
    public java.lang.String getArrivalStation() {
      java.lang.Object ref = arrivalStation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrivalStation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrivalStation = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalStationBytes() {
      java.lang.Object ref = arrivalStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrivalStation = 2;</code>
     */
    public Builder setArrivalStation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrivalStation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalStation = 2;</code>
     */
    public Builder clearArrivalStation() {
      
      arrivalStation_ = getDefaultInstance().getArrivalStation();
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalStation = 2;</code>
     */
    public Builder setArrivalStationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrivalStation_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maths.Stations)
  }

  // @@protoc_insertion_point(class_scope:maths.Stations)
  private static final ds.examples.maths.Stations DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.examples.maths.Stations();
  }

  public static ds.examples.maths.Stations getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Stations>
      PARSER = new com.google.protobuf.AbstractParser<Stations>() {
    @java.lang.Override
    public Stations parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Stations(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Stations> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stations> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.examples.maths.Stations getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

