// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1Timetable.proto

package ds.examples.maths;

public interface TrainNoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maths.TrainNo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trainNo = 1;</code>
   */
  int getTrainNo();
}
