// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1Timetable.proto

package ds.examples.maths;

public interface TrainAmenitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maths.TrainAmenities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string catering = 1;</code>
   */
  java.lang.String getCatering();
  /**
   * <code>string catering = 1;</code>
   */
  com.google.protobuf.ByteString
      getCateringBytes();

  /**
   * <code>string bikeSlot = 2;</code>
   */
  java.lang.String getBikeSlot();
  /**
   * <code>string bikeSlot = 2;</code>
   */
  com.google.protobuf.ByteString
      getBikeSlotBytes();

  /**
   * <code>bool petsAllowed = 3;</code>
   */
  boolean getPetsAllowed();
}
