// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2Booking.proto

package ca.railway.bookingService2.BookingService;

public interface BookingConfirmationMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.railway.bookingService2.BookingConfirmationMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bookingNo = 1;</code>
   */
  int getBookingNo();

  /**
   * <code>int32 trainNo = 2;</code>
   */
  int getTrainNo();

  /**
   * <code>string specialRequestReply = 3;</code>
   */
  java.lang.String getSpecialRequestReply();
  /**
   * <code>string specialRequestReply = 3;</code>
   */
  com.google.protobuf.ByteString
      getSpecialRequestReplyBytes();
}
